/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FullscreenRouteImport } from './routes/fullscreen'
import { Route as IndexRouteImport } from './routes/index'

const FullscreenRoute = FullscreenRouteImport.update({
  id: '/fullscreen',
  path: '/fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fullscreen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fullscreen'
  id: '__root__' | '/' | '/fullscreen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FullscreenRoute: typeof FullscreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fullscreen': {
      id: '/fullscreen'
      path: '/fullscreen'
      fullPath: '/fullscreen'
      preLoaderRoute: typeof FullscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FullscreenRoute: FullscreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
